/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oiza0M2gosO
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
  CarouselItem,
  CarouselContent,
  CarouselPrevious,
  CarouselNext,
  Carousel,
} from "@/components/ui/carousel";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import {
  Car,
  Clock,
  Facebook,
  Instagram,
  MapPin,
  MessageCircle,
  Phone,
} from "lucide-react";
import { Separator } from "./ui/separator";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTiktok, faTwitter } from "@fortawesome/free-brands-svg-icons";

export function Landing() {
  return (
    <div className="flex min-h-[100dvh] flex-col">
      <header className="flex h-14 items-center px-4 lg:px-6">
        <Link className="flex items-center justify-center" href="#">
          <Image
            alt="TAXI La Gi"
            height={60}
            src="/Taxi La Gi LogoV2.png"
            width={200}
          />
        </Link>
        <nav className="ml-auto flex gap-x-1">
          <Link href="https://www.tiktok.com/@hoangvuongthinh">
            <Button variant="ghost" size="icon">
              <FontAwesomeIcon icon={faTiktok} width={24} height={24} />
            </Button>
          </Link>
          {/* need to add a username on Facebook */}
          <Link href="https://www.facebook.com/profile.php?id=61557017503980">
            <Button variant="ghost" size="icon">
              <Facebook />
            </Button>
          </Link>
          <Link href="tel:0962325023">
            <Button variant="ghost" size="icon">
              <Phone />
            </Button>
          </Link>
          {/* <Link href="https://instagram.com/taxilagi">
            <Button variant="ghost" size="icon">
              <Instagram />
            </Button>
          </Link> */}
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full border-y pt-12 md:pt-24 lg:pt-32">
          <div className="space-y-10 px-4 md:px-6 xl:space-y-16">
            <div className="mx-auto grid max-w-[1300px] justify-center gap-4 px-4 sm:px-6 md:grid-cols-2 md:gap-16 md:px-10">
              <div className="flex flex-col justify-center gap-y-3">
                <span className="font-black text-primary">TÀI XẾ RIÊNG</span>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Bạn đi đâu? Đi xe thoải mái cùng Thịnh!
                </h1>
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
                  Chúng tôi cung cấp dịch vụ taxi riêng với xe 4-7 chỗ cho các
                  nhu cầu du lịch, đưa đón sân bay, đám cưới, và các chuyến đi
                  ngắn hoặc dài. Tài xế giàu kinh nghiệm, lịch sự, vận hành xe
                  mới có máy lạnh và wifi.
                </p>
                <div className="mt-6 space-x-4 py-4">
                  <Button variant="default" size="lg">
                    <Link href="tel:0962325023">0962 325 023</Link>
                  </Button>
                  <Button
                    variant="secondary"
                    className="bg-blue-400 hover:bg-blue-300"
                    size="lg"
                  >
                    <Link href="https://zalo.me/0962325023">Zalo</Link>
                  </Button>
                </div>
                <Separator />
                <div className="flex flex-row gap-x-4">
                  <div className="flex flex-row items-center gap-x-2 text-sm">
                    <MessageCircle className="h-6 w-6 text-primary" /> Hỗ trợ
                  </div>
                  <div className="flex flex-row items-center gap-x-2 text-sm">
                    <Clock className="h-6 w-6 text-primary" /> 24/24
                  </div>
                  <div className="flex flex-row items-center gap-x-2 text-sm">
                    <MapPin className="h-6 w-6 text-primary" /> La Gi, Bình
                    Thuận
                  </div>
                </div>
              </div>
              <div className="mt-10 flex flex-col items-start space-y-4">
                <Image
                  alt="Hero"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
                  height="550"
                  src="/Taxi-Lagi-Thinh.jpeg"
                  width="550"
                />
              </div>
            </div>
            <div className="h-12" />
          </div>
        </section>
        <section className="w-full bg-secondary py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Dịch vụ của chúng tôi
                </h2>
                <p className="max-w-[900px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Chúng tôi cung cấp nhiều dịch vụ vận chuyển để đáp ứng nhu cầu
                  của bạn.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Xe đưa đón sân bay</h3>
                <p className="text-sm">
                  Dịch vụ vận chuyển sân bay đáng tin cậy và hiệu quả.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Xe đưa đón doanh nghiệp</h3>
                <p className="text-sm">
                  Dịch vụ vận chuyển chuyên dụng cho nhu cầu kinh doanh của bạn.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Tài xế riêng</h3>
                <p className="text-sm">
                  Tận hưởng sự tiện lợi của tài xế riêng.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Vận chuyển sự kiện</h3>
                <p className="text-sm">
                  Dịch vụ vận chuyển đáng tin cậy cho các sự kiện đặc biệt của
                  bạn.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Tour tham quan thành phố</h3>
                <p className="text-sm">
                  Khám phá thành phố một cách thoải mái với các tour du lịch có
                  hướng dẫn viên của chúng tôi.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Các chuyến đi đường dài</h3>
                <p className="text-sm">
                  Dịch vụ vận chuyển thoải mái và đáng tin cậy cho các chuyến đi
                  đường dài.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Khu vực chúng tôi phục vụ
                </h2>
                <p className="max-w-[900px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Dịch vụ tài xế riêng của chúng tôi có sẵn ở các khu vực sau.
                </p>
              </div>
            </div>
            <div>
              <Image
                alt="Khu vực chúng tôi phục vụ"
                height="600"
                src="/TAXI La Gi, Binh Thuan map.png"
                width="800"
                className="mx-auto rounded-lg object-cover"
              />
            </div>
            {/* <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">New York City</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Serving all five boroughs of New York City.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Los Angeles</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Providing transportation throughout the LA metro area.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Chicago</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Serving the greater Chicago metropolitan region.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Miami</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Covering Miami and the surrounding South Florida area.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Boston</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Serving the greater Boston metropolitan region.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Washington, D.C.</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Providing transportation throughout the D.C. metro area.
                </p>
              </div>
            </div> */}
          </div>
        </section>
        <section className="w-full bg-secondary py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Hình ảnh
                </h2>
                <p className="max-w-[900px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Xem hình ảnh của các xe và tài xế của chúng tôi.
                </p>
              </div>
            </div>
            <div className="mx-auto w-full max-w-6xl">
              <Carousel className="w-full">
                <CarouselContent>
                  <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                    <Image
                      alt="Ca 1 "
                      className="aspect-video rounded-lg object-cover object-bottom"
                      height={400}
                      src="/lagi-taxi.jpg"
                      width={800}
                    />
                  </CarouselItem>
                  <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                    <Image
                      alt="Car 3"
                      className="aspect-video rounded-lg object-cover"
                      height={400}
                      src="/Taxi-Lagi-Thinh.jpeg"
                      width={800}
                    />
                  </CarouselItem>
                  <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                    <Image
                      alt="Car 3"
                      className="zoom aspect-video rounded-lg object-cover object-bottom"
                      height={400}
                      src="/airport.jpg"
                      width={800}
                    />
                  </CarouselItem>

                  <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                    <Image
                      alt="Car 2"
                      className="aspect-video rounded-lg object-cover"
                      height={400}
                      src="/TAXI La Gi, Binh Thuan map.png"
                      width={800}
                    />
                  </CarouselItem>
                </CarouselContent>
                <CarouselPrevious />
                <CarouselNext />
              </Carousel>
            </div>
          </div>
        </section>
        {/* <section className="w-full bg-gray-100 py-12 dark:bg-gray-800 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Get in Touch
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Fill out the form below to request a quote or book your private
                driver service.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col space-y-4">
                <Input
                  className="max-w-lg flex-1"
                  placeholder="Name"
                  type="text"
                />
                <Input
                  className="max-w-lg flex-1"
                  placeholder="Email"
                  type="email"
                />
                <Textarea className="max-w-lg flex-1" placeholder="Message" />
                <Button className="justify-self-start" type="submit">
                  Submit
                </Button>
              </form>
              <div className="flex items-center justify-center gap-4">
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="#"
                >
                  <FacebookIcon className="h-5 w-5" />
                </Link>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="#"
                >
                  <TwitterIcon className="h-5 w-5" />
                </Link>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="#"
                >
                  <InstagramIcon className="h-5 w-5" />
                </Link>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="#"
                >
                  <PhoneIcon className="h-5 w-5" />
                </Link>
              </div>
            </div>
          </div>
        </section> */}
      </main>
      <footer className="flex w-full shrink-0 flex-col items-center justify-center gap-2 border-t px-4 py-6 sm:flex-row md:px-6">
        <p className="text-xs text-muted-foreground">© 2024 TAXI La Gi |</p>
        <p className="text-xs text-muted-foreground">
          <Link
            href="https://derekcowan.com"
            className="underline hover:text-primary"
          >
            Site Design by DerekCowan
          </Link>
        </p>
        {/* <nav className="flex gap-4 sm:ml-auto sm:gap-6">
          <Link className="text-xs underline-offset-4 hover:underline" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs underline-offset-4 hover:underline" href="#">
            Privacy Policy
          </Link>
        </nav> */}
      </footer>
    </div>
  );
}

// function CarIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
//       <circle cx="7" cy="17" r="2" />
//       <path d="M9 17h6" />
//       <circle cx="17" cy="17" r="2" />
//     </svg>
//   );
// }

// function FacebookIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
//     </svg>
//   );
// }

// function InstagramIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
//       <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
//       <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
//     </svg>
//   );
// }

// function PhoneIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
//     </svg>
//   );
// }

// function TwitterIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
//     </svg>
//   );
// }
